-- В схеме DEVELOPER
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE DEVELOPER.T1 DROP CONSTRAINT tab1_c1_fk';
    EXECUTE IMMEDIATE 'ALTER TABLE DEVELOPER.T3 DROP CONSTRAINT tab3_c1_fk';
    EXECUTE IMMEDIATE 'DROP TABLE DEVELOPER.T1 CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE DEVELOPER.T2 CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE DEVELOPER.T3 CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE DEVELOPER.LoopTable CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE DEVELOPER.TertiaryRef CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE DEVELOPER.SecondaryRef CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE DEVELOPER.BaseReference CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE DEVELOPER.TestAgain CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE DEVELOPER.NowTask CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE DEVELOPER.OSISP CASCADE CONSTRAINTS';
END;
/

-- В схеме PRODUCTION
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE PRODUCTION.DataStore CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE PRODUCTION.NowTask CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE PRODUCTION.OSISP CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE PRODUCTION.AdditionalData CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE PRODUCTION.TestAgain CASCADE CONSTRAINTS';
END;
/

-- В схеме DEVELOPER
BEGIN
    EXECUTE IMMEDIATE 'DROP PROCEDURE DEVELOPER.executeStepOne';
    EXECUTE IMMEDIATE 'DROP PROCEDURE DEVELOPER.performActionTwo';
    EXECUTE IMMEDIATE 'DROP PROCEDURE DEVELOPER.handleStepThree';
    EXECUTE IMMEDIATE 'DROP PROCEDURE DEVELOPER.TestProc';
    EXECUTE IMMEDIATE 'DROP FUNCTION DEVELOPER.CalculateValue';
END;
/

-- В схеме PRODUCTION
BEGIN
    EXECUTE IMMEDIATE 'DROP PROCEDURE PRODUCTION.executeStepOne';
    EXECUTE IMMEDIATE 'DROP PROCEDURE PRODUCTION.performActionTwo';
    EXECUTE IMMEDIATE 'DROP PROCEDURE PRODUCTION.specialOperation';
END;
/
