-- В схеме DEVELOPER
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE DEVELOPER.T1 DROP CONSTRAINT tab1_c1_fk';
    EXECUTE IMMEDIATE 'ALTER TABLE DEVELOPER.T3 DROP CONSTRAINT tab3_c1_fk';
    EXECUTE IMMEDIATE 'DROP TABLE DEVELOPER.T1 CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE DEVELOPER.T2 CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE DEVELOPER.T3 CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE DEVELOPER.LoopTable CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE DEVELOPER.TertiaryRef CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE DEVELOPER.SecondaryRef CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE DEVELOPER.BaseReference CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE DEVELOPER.TestAgain CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE DEVELOPER.NowTask CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE DEVELOPER.OSISP CASCADE CONSTRAINTS';
END;
/

-- В схеме PRODUCTION
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE PRODUCTION.DataStore CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE PRODUCTION.NowTask CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE PRODUCTION.OSISP CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE PRODUCTION.AdditionalData CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE PRODUCTION.TestAgain CASCADE CONSTRAINTS';
END;
/

-- В схеме DEVELOPER
BEGIN
    EXECUTE IMMEDIATE 'DROP PROCEDURE DEVELOPER.executeStepOne';
    EXECUTE IMMEDIATE 'DROP PROCEDURE DEVELOPER.performActionTwo';
    EXECUTE IMMEDIATE 'DROP PROCEDURE DEVELOPER.handleStepThree';
    EXECUTE IMMEDIATE 'DROP PROCEDURE DEVELOPER.TestProc';
    EXECUTE IMMEDIATE 'DROP FUNCTION DEVELOPER.CalculateValue';
END;
/

-- В схеме PRODUCTION
BEGIN
    EXECUTE IMMEDIATE 'DROP PROCEDURE PRODUCTION.executeStepOne';
    EXECUTE IMMEDIATE 'DROP PROCEDURE PRODUCTION.performActionTwo';
    EXECUTE IMMEDIATE 'DROP PROCEDURE PRODUCTION.specialOperation';
END;
/


-- Удаление таблиц с внешними ключами в правильном порядке
DROP TABLE DEVELOPER.t1 CASCADE CONSTRAINTS; -- Удаляем t1, которая ссылается на t3
DROP TABLE DEVELOPER.t3 CASCADE CONSTRAINTS; -- Удаляем t3, которая ссылается на t2
DROP TABLE DEVELOPER.t2 CASCADE CONSTRAINTS; -- Удаляем t2

-- Удаление таблицы table1, которая существует в обеих схемах
DROP TABLE DEVELOPER.table1 CASCADE CONSTRAINTS;
DROP TABLE PRODUCTION.table1 CASCADE CONSTRAINTS;

-- Удаление таблицы my_table, которая существует в обеих схемах
DROP TABLE DEVELOPER.my_table CASCADE CONSTRAINTS;
DROP TABLE PRODUCTION.my_table CASCADE CONSTRAINTS;

-- Удаление процедур
DROP PROCEDURE DEVELOPER.my_procedure;
DROP PROCEDURE PRODUCTION.my_procedure;


BEGIN
    EXECUTE IMMEDIATE 'DROP TYPE dep_rec';
    EXECUTE IMMEDIATE 'DROP TYPE dep_tab';
EXCEPTION
    WHEN OTHERS THEN
        NULL;  -- Игнорировать ошибку, если типы не существуют
END;

SELECT * FROM all_tab_privs WHERE grantee = USER;

SELECT * FROM session_privs;

SELECT COUNT(*) INTO v_count FROM all_users WHERE username = UPPER('DEVELOPER');


SELECT * FROM user_role_privs;

SELECT * 
FROM all_dependencies 
WHERE referenced_type = 'TYPE' 
  AND referenced_name = 'DEP_REC';

  DROP TYPE dep_rec CASCADE;


DROP TYPE dep_rec FORCE;
DROP TYPE dep_tab FORCE;

GRANT SELECT ANY TABLE TO SYSTEM;
GRANT SELECT_CATALOG_ROLE TO SYSTEM;


SELECT owner, name, type 
FROM all_dependencies 
WHERE referenced_name IN ('DEP_REC', 'DEP_TAB');

SELECT username FROM all_users WHERE username IN ('DEVELOPER', 'PRODUCTION');
SELECT username FROM all_users WHERE username IN ('DEVELOPER', 'PRODUCTION');

CONNECT SYS AS SYSDBA;

GRANT SELECT ON ALL_TAB_COLUMNS TO SYSTEM;
GRANT SELECT ON ALL_CONSTRAINTS TO SYSTEM;
GRANT SELECT ON ALL_CONS_COLUMNS TO SYSTEM;
GRANT SELECT ON ALL_TABLES TO SYSTEM;
GRANT SELECT ON ALL_USERS TO SYSTEM;


GRANT SELECT ANY TABLE TO SYSTEM;

ALTER USER DEVELOPER IDENTIFIED BY admin;
ALTER USER PRODUCTION IDENTIFIED BY admin;


SELECT username FROM all_users WHERE username IN ('DEVELOPER', 'PRODUCTION');

