create table DEVELOPER.my_table(
    id number PRIMARY KEY,
    name VARCHAR2(100)
);

CREATE TABLE PRODUCTION.my_table (
    id NUMBER PRIMARY KEY,
    name VARCHAR2(100),
    description VARCHAR2(255)
);


EXECUTE GENERATE_SYNC_SCRIPT('DEVELOPER', 'PRODUCTION');

BEGIN
    compare_schemas('DEVELOPER', 'PRODUCTION');
END;
/



CREATE TABLE DEVELOPER.t2 (
    id NUMBER PRIMARY KEY,
    name VARCHAR2(100)
);


CREATE TABLE DEVELOPER.t3 (
    id NUMBER PRIMARY KEY,
    name VARCHAR2(100),
    t2_id NUMBER,
    CONSTRAINT fk_t2 FOREIGN KEY (t2_id) REFERENCES DEVELOPER.t2(id)
);


CREATE TABLE DEVELOPER.t1 (
    id NUMBER PRIMARY KEY,
    name VARCHAR2(100),
    t3_id NUMBER,
    CONSTRAINT fk_t3 FOREIGN KEY (t3_id) REFERENCES DEVELOPER.t3(id)
);

EXECUTE GENERATE_SYNC_SCRIPT('DEVELOPER', 'PRODUCTION');


CREATE TABLE DEVELOPER.table1 (
    id NUMBER PRIMARY KEY,
    name VARCHAR2(100)
);

CREATE TABLE PRODUCTION.table1 (
    id VARCHAR2(100) PRIMARY KEY, 
    name VARCHAR2(100)
);

EXECUTE GENERATE_SYNC_SCRIPT('DEVELOPER', 'PRODUCTION');

BEGIN
    compare_schemas('DEVELOPER', 'PRODUCTION');
END;
/



CREATE OR REPLACE PROCEDURE DEVELOPER.my_procedure IS
BEGIN
    DBMS_OUTPUT.PUT_LINE('Это процедура в Dev Schema');
END;
/


CREATE OR REPLACE PROCEDURE PRODUCTION.my_procedure IS
BEGIN
    DBMS_OUTPUT.PUT_LINE('Это процедура в Prod Schema');
END;
/

EXECUTE GENERATE_SYNC_SCRIPT('DEVELOPER', 'PRODUCTION');